#ifndef ASTRA_COMPOSITE_BLOOM_FSH
#define ASTRA_COMPOSITE_BLOOM_FSH

/*
 * AstraRealism - Bloom.
 *
 * Two passes share this body, selected by ASTRA_BLOOM_STAGE:
 *
 *   1  bright pass   extract what should bloom into colortex12
 *   2  combine       walk the mip pyramid and mix it back into the scene
 *
 * The downsample between them is the hardware mip chain, generated by Iris when
 * the combine pass declares colortex12MipmapEnabled. Seven levels would
 * otherwise need seven render passes.
 */

#include "/lib/common/common.glsl"
#include "/lib/post/bloom.glsl"
#include "/lib/post/lens.glsl"

#ifndef ASTRA_BLOOM_STAGE
    #define ASTRA_BLOOM_STAGE 1
#endif

in vec2 texcoord;

#if ASTRA_BLOOM_STAGE == 1

/* RENDERTARGETS: 12 */
layout(location = 0) out vec4 bloomTarget;

void main() {
    vec3 scene = texture(colortex0, texcoord).rgb;

    bloomTarget = vec4(bloomBrightPass(scene), 1.0);
}

#else

/*
 * Iris generates the mip chain for this buffer before the pass runs, which is
 * the whole reason the downsample costs nothing.
 */
// Valid GLSL, so emitted as real code rather than as a directive in a
// block comment - only the format names need that treatment.
const bool colortex12MipmapEnabled = true;

/* RENDERTARGETS: 0 */
layout(location = 0) out vec4 sceneColor;

void main() {
    vec3 scene = texture(colortex0, texcoord).rgb;

#if !ASTRA_ENABLE_BLOOM
    sceneColor = vec4(scene, 1.0);
#else
    vec3 bloom = gatherBloom(colortex12, texcoord);

    vec3 result = applyBloom(scene, bloom);

    /*
     * Lens dirt belongs here rather than in the final pass, because it
     * modulates the bloom specifically - dirt on the front element is only
     * visible when something bright scatters off it. Applied after the combine
     * so it adds to, rather than replaces, the clean glow.
     */
    result = applyLensDirt(result, bloom, texcoord);

    sceneColor = vec4(result, 1.0);
#endif
}

#endif

#endif // ASTRA_COMPOSITE_BLOOM_FSH
